name: Build & Test

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  tests-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Install Bun
      run: npm install -g bun
    - name: Install dependencies
      run: bun install
    - name: Biome Check
      run: bunx biome check
    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps
    - name: Prepare the application
      run:  bun run generate
    - name: Build the playground
      run:  bun run dev:build
    - name: Run Playwright tests
      run: bunx playwright test
    - uses: daun/playwright-report-summary@v3
      if: always()
      with:
        report-file: results.json
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30